version: '3.8'

services:
  validator:
    image: gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.4.0
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      RUST_LOG: debug
      CONFIG_FILES: /hyperlane/config/agent.json
    container_name: validator
    volumes:
      - ./config:/hyperlane/config
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
