version: '3.8'

services:
  validator:
    image: gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.1.0
    container_name: validator
    volumes:
      - ./config:/hyperlane/config
    environment:
      - RUST_LOG=debug
      - CONFIG_FILES=/hyperlane/config/agent.json
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
