# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xDBBa0C6950286eA36f7128565D55F14b28e86906"
    chainName: apechain
    connections:
      - token: ethereum|rarichain|0xDBBa0C6950286eA36f7128565D55F14b28e86906
    decimals: 18
    name: CC WETH
    standard: EvmHypSynthetic
    symbol: WETH
  - addressOrDenom: "0xDBBa0C6950286eA36f7128565D55F14b28e86906"
    chainName: rarichain
    connections:
      - token: ethereum|apechain|0xDBBa0C6950286eA36f7128565D55F14b28e86906
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: WETH
