# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x09635F643e140090A9A8Dcd712eD6285858ceBef"
    chainName: source
    connections:
      - token: ethereum|destination|0x09635F643e140090A9A8Dcd712eD6285858ceBef
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ECWETH
  - addressOrDenom: "0x09635F643e140090A9A8Dcd712eD6285858ceBef"
    chainName: destination
    connections:
      - token: ethereum|source|0x09635F643e140090A9A8Dcd712eD6285858ceBef
    decimals: 18
    name: Espresso Composables WETH
    standard: EvmHypSynthetic
    symbol: ECWETH
