# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x95401dc811bb5740090279Ba06cfA8fcF6113778"
    chainName: destination
    connections:
      - token: ethereum|source|0x95401dc811bb5740090279Ba06cfA8fcF6113778
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ECWETH
  - addressOrDenom: "0x95401dc811bb5740090279Ba06cfA8fcF6113778"
    chainName: source
    connections:
      - token: ethereum|destination|0x95401dc811bb5740090279Ba06cfA8fcF6113778
    decimals: 18
    name: Espresso Composables WETH
    standard: EvmHypSynthetic
    symbol: ECWETH
