defaultHook:
  beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  oracleConfig:
    destination:
      gasPrice: "1058512358"
      tokenDecimals: 18
      tokenExchangeRate: "11000000000"
  oracleKey: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  overhead:
    destination: 75000
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: interchainGasPaymaster
defaultIsm:
  threshold: 1
  type: messageIdMultisigIsm
  validators:
    - "0xcb7825cbf2C92c3acfbb98A2296A6693bcbD078C"
owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
proxyAdmin:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
requiredHook:
  beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  oracleConfig:
    destination:
      gasPrice: "1058512358"
      tokenDecimals: 18
      tokenExchangeRate: "11000000000"
  oracleKey: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  overhead:
    destination: 75000
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: interchainGasPaymaster


