owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
defaultIsm:
  type: trustedRelayerIsm
  relayer: "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f"
defaultHook:
  type: aggregationHook
  hooks:
    - owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      type: interchainGasPaymaster
      beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      oracleKey: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      overhead:
        destination: 75000
      oracleConfig:
        destination:
          gasPrice: "1000000007"
          tokenExchangeRate: "11000000000"
          tokenDecimals: 18
    - type: merkleTreeHook
requiredHook:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: interchainGasPaymaster
  beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  oracleKey: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  overhead:
    destination: 75000
  oracleConfig:
    destination:
      gasPrice: "1000000007"
      tokenExchangeRate: "11000000000"
      tokenDecimals: 18
proxyAdmin:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

