# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x29b0a57Cb774f513653a90d3a185eb12D4AAc3ad"
    chainName: rarichain
    connections:
      - token: ethereum|apechain|0x29b0a57Cb774f513653a90d3a185eb12D4AAc3ad
    decimals: 18
    name: Espresso Presto WAPE
    standard: EvmHypSynthetic
    symbol: EPWAPE
  - addressOrDenom: "0x29b0a57Cb774f513653a90d3a185eb12D4AAc3ad"
    chainName: apechain
    connections:
      - token: ethereum|rarichain|0x29b0a57Cb774f513653a90d3a185eb12D4AAc3ad
    decimals: 18
    name: Ape
    standard: EvmHypNative
    symbol: EPWAPE
