name: E2E Tests

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    branches:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci
  SERVICES_LOGS: /tmp/xchain-services.log

jobs:
  e2e-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Install process-compose
        run: nix profile install nixpkgs#process-compose
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.3.5
      - uses: taiki-e/install-action@just

      - name: Install solidity deps
        run: just install

      - name: Build all contracts
        run: just build

      - name: Fix Docker volume permissions
        run: |
          echo "Current user: $(id)"
          echo "Docker container runs as: $(docker run --rm gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.4.0 id)"
          ls -la anvil/hyperlane/validator-relayer-setup/source/hyperlane_db || true
          ls -la anvil/hyperlane/validator-relayer-setup/relayer/hyperlane_db || true
          sudo chown -R 1000:1000 anvil/hyperlane/validator-relayer-setup/source/hyperlane_db || true
          sudo chown -R 1000:1000 anvil/hyperlane/validator-relayer-setup/relayer/hyperlane_db || true

      - name: Launch services
        run: |
          just launch 2>&1 | tee $SERVICES_LOGS &
          sleep 5

      - name: Inspect relayer docker image
        run: docker inspect relayer

      - name: Inspect validator docker image
        run: docker inspect source-validator

      - name: Run E2E tests
        run: just test-e2e

      - name: Upload service logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xchain-services-logs
          path: ${{ env.SERVICES_LOGS }}
